import { GovernmentBuilding, GovernmentBuildingType } from '../types/buildings';
import { LocationContext } from '../types/civic';

export function getGovernmentBuildings(location: LocationContext): GovernmentBuilding[] {
  const { city, county, state, stateCode, lat, lng } = location;

  return [
    {
      id: `bldg-city-hall-${city.toLowerCase()}`,
      name: `${city} City Hall & Municipal Complex`,
      type: 'city_hall',
      typeLabel: 'Municipal City Hall',
      pieceTheme: 'gold',
      lat: lat + 0.0035,
      lng: lng - 0.0042,
      address: `100 Main St, ${city}, ${stateCode}`,
      jurisdictionLevel: 'local',
      occupants: [
        `Office of the Mayor`,
        `${city} City Council Chambers`,
        `Department of Planning & Zoning`,
        `City Clerk's Public Records Office`,
      ],
      publicServices: [
        'Building Permits & Zoning Inspections',
        'Municipal Utility Billing',
        'Public Hearing Witness Sign-up',
        'Voter Registration & Municipal Licenses',
      ],
      hours: 'Mon – Fri: 8:00 AM – 5:00 PM',
      phone: '(555) 201-4000',
      websiteUrl: `https://${city.toLowerCase().replace(/\s+/g, '')}.gov/city-hall`,
      upcomingHearing: {
        title: 'City Council Regular Session',
        room: 'Chambers Room 201',
        time: 'Tuesday, 7:00 PM',
      },
      boardGamePieceDescription: 'Monopoly Town Hall token in polished brass with 3D portico pediment and clock tower.',
    },
    {
      id: `bldg-courthouse-${county.toLowerCase()}`,
      name: `${county} Courthouse & Justice Center`,
      type: 'courthouse',
      typeLabel: 'County Courthouse',
      pieceTheme: 'bronze',
      lat: lat - 0.0048,
      lng: lng + 0.0038,
      address: `202 E. Washington Ave, ${city}, ${stateCode}`,
      jurisdictionLevel: 'county',
      occupants: [
        `${county} Circuit & District Courts`,
        `County Board of Commissioners Meeting Hall`,
        `County Recorder of Deeds & Vital Records`,
        `County Treasurer & Property Assessment`,
      ],
      publicServices: [
        'Marriage Licenses & Vital Records',
        'Property Tax Payments & Assessment Appeals',
        'Jury Duty Reporting',
        'Small Claims & Civil Court Filings',
      ],
      hours: 'Mon – Fri: 8:30 AM – 4:30 PM',
      phone: '(555) 349-8000',
      websiteUrl: `https://${county.toLowerCase().replace(/\s+/g, '')}.gov/courthouse`,
      upcomingHearing: {
        title: 'Board of Commissioners Fiscal Hearing',
        room: 'Courtroom 3A',
        time: 'Thursday, 6:30 PM',
      },
      boardGamePieceDescription: 'Tabletop justice temple token with ionic pillars and scale of justice crest.',
    },
    {
      id: `bldg-capitol-${stateCode.toLowerCase()}`,
      name: `${state} State Capitol & Legislative Assembly`,
      type: 'state_capitol',
      typeLabel: 'State Capitol',
      pieceTheme: 'pewter',
      lat: lat + 0.0082,
      lng: lng + 0.0075,
      address: `Capitol Complex, 401 S. Spring St, Capital District, ${stateCode}`,
      jurisdictionLevel: 'state',
      occupants: [
        `Governor's Executive Office`,
        `State Senate & House of Representatives Chambers`,
        `State Supreme Court Hearing Chambers`,
        `Legislative Reference Bureau`,
      ],
      publicServices: [
        'State Legislative Committee Hearings',
        'State Constituent Casework Services',
        'State Historical Archives & Rotunda Tours',
        'Executive Ethics Disclosures Access',
      ],
      hours: 'Mon – Fri: 8:00 AM – 5:30 PM (Public Rotunda Tours: 9 AM - 4 PM)',
      phone: '(555) 782-2000',
      websiteUrl: `https://capitol.${stateCode.toLowerCase()}.gov`,
      upcomingHearing: {
        title: 'Senate Appropriations Committee Hearing',
        room: 'Senate Hearing Room 400',
        time: 'Wednesday, 10:00 AM',
      },
      boardGamePieceDescription: 'Grand Wonder Monument piece with tiered 3D rotunda dome and flagpole spire.',
    },
    {
      id: `bldg-fed-${stateCode.toLowerCase()}`,
      name: `U.S. Federal Building & Congressional District Office`,
      type: 'federal_building',
      typeLabel: 'Federal Building',
      pieceTheme: 'sapphire',
      lat: lat - 0.0062,
      lng: lng - 0.0055,
      address: `Federal Center, 300 S. 4th St, ${city}, ${stateCode}`,
      jurisdictionLevel: 'federal',
      occupants: [
        `U.S. House of Representatives District Office (Dist ${location.congressionalDistrict})`,
        `U.S. Senator Regional Constituent Services Office`,
        `United States District Court (Clerk's Office)`,
        `Federal Information Center`,
      ],
      publicServices: [
        'Federal Agency Assistance (VA, Social Security, IRS Casework)',
        'Congressional Commendations & Flag Requests',
        'Federal Passport Agency Expedited Intake',
        'U.S. Service Academy Nominations',
      ],
      hours: 'Mon – Fri: 8:30 AM – 5:00 PM (Security screening required)',
      phone: '(555) 892-1200',
      websiteUrl: `https://gsa.gov/buildings/${city.toLowerCase().replace(/\s+/g, '')}`,
      boardGamePieceDescription: 'Classical Federal monolith piece with eagle crest and architectural balustrade.',
    },
    {
      id: `bldg-safety-${city.toLowerCase()}`,
      name: `${city} / ${county} Public Safety & Emergency Operations HQ`,
      type: 'public_safety',
      typeLabel: 'Public Safety & Sheriff HQ',
      pieceTheme: 'crimson',
      lat: lat + 0.0058,
      lng: lng - 0.0092,
      address: `505 S. 1st St, ${city}, ${stateCode}`,
      jurisdictionLevel: 'county',
      occupants: [
        `${county} Sheriff's Department`,
        `${city} Police Headquarters`,
        `County 911 Communications & Dispatch Authority`,
        `Emergency Management Operations Center (EOC)`,
      ],
      publicServices: [
        'Non-Emergency Police & Sheriff Reports',
        'Community Safety & Neighborhood Watch Inquiries',
        'Fingerprinting & Background Check Intake',
        'Emergency Preparedness Alerts Registration',
      ],
      hours: '24/7 Dispatch · Public Counter: 8:00 AM – 6:00 PM',
      phone: '(555) 349-8900',
      websiteUrl: `https://${city.toLowerCase().replace(/\s+/g, '')}.gov/safety`,
      boardGamePieceDescription: 'Carcassonne-style fortified bastion watchtower piece with golden shield emblem.',
    },
    {
      id: `bldg-library-${city.toLowerCase()}`,
      name: `${city} Public Library & Municipal Archives`,
      type: 'library',
      typeLabel: 'Civic Library & Open Archives',
      pieceTheme: 'emerald',
      lat: lat - 0.0025,
      lng: lng + 0.0085,
      address: `200 W. Green St, ${city}, ${stateCode}`,
      jurisdictionLevel: 'local',
      occupants: [
        `Main Public Library & Community Learning Center`,
        `City Historical Records & Map Archives`,
        `Civic Meeting Rooms & Public Forum Hall`,
        `Digital Government Access Lab`,
      ],
      publicServices: [
        'Historical Municipal Ordinances & Map Archives',
        'Free Public Computer & Internet Terminals',
        'Civic Meeting Room Reservations',
        'Public Notary & Government Form Assistance',
      ],
      hours: 'Mon – Thu: 9 AM – 9 PM, Fri – Sat: 9 AM – 6 PM, Sun: 1 PM – 5 PM',
      phone: '(555) 403-2000',
      websiteUrl: `https://${city.toLowerCase().replace(/\s+/g, '')}publiclibrary.org`,
      boardGamePieceDescription: 'Tabletop academy token with open book pediment and carved portico.',
    },
  ];
}
