import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import { registry, root, sites, availableSites } from './site-registry.mjs';

function writeChanged(file, body) {
  if (!existsSync(file) || readFileSync(file, 'utf8') !== body) writeFileSync(file, body);
}
export function syncSiteHandlers() {
  const generated = join(root, '.generated');
  mkdirSync(generated, { recursive: true });
  const imports = [],
    handlers = [];
  for (const [index, site] of sites.entries()) {
    const entry = ['server.ts', 'server.js']
      .map((name) => join(site.directory, name))
      .find(existsSync);
    if (!entry) continue;
    imports.push(
      `import { handleApi as handler${index} } from ${JSON.stringify('../' + relative(root, entry).replaceAll('\\', '/'))};`,
    );
    handlers.push(`${JSON.stringify(site.username)}: handler${index}`);
  }
  writeChanged(
    join(generated, 'site-handlers.js'),
    `// Generated from sites.config.json and each site's optional server.ts/server.js.\n${imports.join('\n')}\n/** @type {Record<string, (request: Request, env: Record<string, any>, path: string) => Promise<Response>>} */\nexport const siteHandlers = {${handlers.join(',')}};\n`,
  );
}
export function renderPortal() {
  const available = new Set(availableSites().map((site) => site.username));
  const links = sites
    .map((site, index) =>
      available.has(site.username)
        ? `<a class="site" href="${site.basePath}/"><span>${String(index + 1).padStart(2, '0')}</span><strong>${site.username}</strong><i>Enter ↗</i></a>`
        : `<div class="site site-pending"><span>${String(index + 1).padStart(2, '0')}</span><strong>${site.username}</strong><i>Coming soon</i></div>`,
    )
    .join('\n        ');
  return readFileSync(join(root, 'portal/index.html'), 'utf8').replace(
    '<!-- SITE_DIRECTORY -->',
    links,
  );
}
export function renderHeaders() {
  return sites
    .map(
      (site) =>
        `${site.basePath}/data/manifest.json\n  Cache-Control: public, max-age=60, must-revalidate\n\n${site.basePath}/data/releases/*\n  Cache-Control: public, max-age=31536000, immutable\n\n${site.basePath}/_app/immutable/*\n  Cache-Control: public, max-age=31536000, immutable\n`,
    )
    .join('\n');
}
export function renderCodeowners() {
  const all = sites.map((site) => `@${site.username}`).join(' ');
  return `# Generated by npm run sites:sync from sites.config.json.\n# Shared files can be reviewed by any registered collaborator.\n* ${all}\n\n${sites
    .map(
      (site) =>
        `/sites/${site.username}/ @${site.username} ${sites
          .filter(
            (other) =>
              other.username !== site.username &&
              (site.username === registry.defaultSite || other.username === registry.defaultSite),
          )
          .map((other) => `@${other.username}`)
          .join(' ')}`,
    )
    .join('\n')}\n\n/.github/CODEOWNERS ${all}\n`;
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  syncSiteHandlers();
  writeChanged(join(root, '.github/CODEOWNERS'), renderCodeowners());
  console.log(`Synced ${sites.length} registered sites.`);
}
